import "./globals.css";
import type { Metadata } from "next";
import { Space_Grotesk, Archivo_Narrow } from "next/font/google";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-sans-primary",
  subsets: ["latin"],
});
const archivoNarrow = Archivo_Narrow({
  variable: "--font-sans-alt",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={[spaceGrotesk.variable, archivoNarrow.variable].join(" ")}
      >
        {children}
      </body>
    </html>
  );
}
